version: 0.2  # CodeDeploy 버전
os: linux
files:
  - source: /    # CodeDeploy에서 전달해 준 파일 중 destination으로 이동시킬 대상을 루트로 지정(전체파일)
    destination: /home/ec2-user/app  # source에서 지정된 파일을 받을 위치
    overwrite: yes

permissions: # CodeDeploy에서 EC2서버로 넘겨준 파일들은 모두 ec2-user권한을 갖도록 설정
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:  # 배포를 완료한 후 실행되는 스크립트
    - location: restart.sh
      timeout: 60
      runas: ec2-user